### ISSUE TITLE
Input handler

### ISSUE THREAD

**Issue by SebastianJay** [SebastianJay/Wilderness#2]
Our input handler will wait for keystrokes from the user and put them onto a globally accessible queue. We will want to keep this handler in a separate thread so the loop in our main thread can run the update/render code.

Write a loop that captures keystroke inputs and enqueues them as a (key_id, state) tuple, where key_id says which key it is (like 'a' for the A key) and state says whether it is being pushed down or up. Certain meta keys like Shift may need some special treatment.

Once this is done, create a "listener" that we can insert in the main loop that, during the update phase, will poll the queue and create a model of which keys have been pressed and which keys have been held down (for e.g. Shift) on this cycle.

(If there's an easy way to do this, great. Cursory web searches suggest otherwise)

Possible starting point: http://stackoverflow.com/questions/11918999/key-listeners-in-python

**Comment by winstliu** [comment]
So it looks like we can't use curses because it's 2016 and Windows is still incompatible with everything.  Out of the remaining options from the accepted answer, termios is also Windows-incompatible, PDCurses hasn't been updated since 2008 (and hence is probably python2 only...will check later), and pywin32 is 403ing.  :unamused:

**Comment by SebastianJay** [comment]
Strange to see no easy Python way to do this.

Based on what we've seen in #3, I'm planning to go ahead with tkinter. At least in that library there seems to be ways to listen to input events. If that works, let's try to isolate the input part in its own file.

Take a look here: http://effbot.org/tkinterbook/tkinter-events-and-bindings.htm

**Comment by winstliu** [comment]
Work is ongoing in https://github.com/SebastianJay/Wilderness/tree/wl-input-handler.

**Comment by winstliu** [comment]
From what I can tell, there doesn't seem to be a way to determine whether the key is being pressed or released, only that it's currently being active.  Thankfully, while Shift is captured as its own key, any keys that are pressed while Shift is held down are captured as the shifted variant (eg `S` instead of just `s`).

**Comment by SebastianJay** [comment]
OK, what does "active" mean? If I hold a key down, does the event trigger multiple times?

The shift behavior seems pretty convenient -- we can probably just go with it.

Ultimately, what InputHandler should expose is a queue that a main loop can poll to get keystrokes. I'm unsure if thread safety is a concern -- if it is, then it might be better to have backspace as its own character (`'\b'`)

**Comment by winstliu** [comment]
> If I hold a key down, does the event trigger multiple times?

Yep.

**Comment by SebastianJay** [comment]
OK, we can keep that behavior as well if it's similar to what you observe in a text editor when the key is held down.

The [Queue class](https://docs.python.org/3/library/asyncio-queue.html) would be what I'd look at for buffering the keystrokes.

Also, if we keep backspace as its own character, implementing something like "Press enter to continue" would be more robust since if a user presses Enter and Backspace quickly neither keystroke will be seen by the consumer of InputHandler (so it would seem like Enter was never pressed).

So most keystrokes will go in the queue, metakeys like Shift and Ctrl can set some bools high while they are active.

**Comment by winstliu** [comment]
Can I have an example of how coroutines work?  I'm not quite understanding all the `await`/`async def` syntax.

**Comment by SebastianJay** [comment]
I'm not sure we need actually need the async semantics, just a Queue so we have a producer-consumer "pipeline."

`onKeyPressed()` will be the producer that will enqueue elements. We can expose some other method like `getKeyPresses()` in `InputHandler` which will be the consumer that gets called from the main loop in `main.py`. The consumer will empty the queue and return the list of keypresses so that main can in turn pass it along to the Window classes.

See https://pymotw.com/2/Queue/#basic-fifo-queue -- `get` and `put` are all we need
