### ISSUE TITLE
Investigate tkinter

### ISSUE THREAD

**Issue by SebastianJay** [SebastianJay/Wilderness#3]
We will try tkinter as our graphics engine. All code interfacing with tkinter libraries should go into the Display class, and Display will interact with WindowManager to get an abstract view of what should go on screen. Let's say WindowManager exposes a 2D array of chars (a list of list of 1 char strings) to Display.

Play around with tkinter with a monospace font and answer the following questions.
- Can we efficiently render a 2D array of characters (at 30 FPS, i.e. run a loop that runs 1/30 of a second and continuously makes multiple draw string calls that are 1 character long)?
- Can we draw different colors?
- Can we draw different styles (italics, bold, underline)?
- Any other cool text drawing features

Possible starting point: http://www.tutorialspoint.com/python/tk_text.htm

**Comment by SebastianJay** [comment]
@yj7082126 Can you please follow up on what you found with tkinter? Specifically, I'm wondering about the performance, because it determines design decisions for the Window classes (which other people work on) -- it is possible to do many "draw string" commands (one for each character) at 30 FPS? On my screen, I can fit 170x40 = 6800 chars of 12 pt monospaced font, so for e.g. is 6800 commands feasible? If not, what is the threshold?

**Comment by SebastianJay** [comment]
The follow on to this task is to implement a `Display.draw()` method that takes in a 2D char array (in Python, a list of lists of strings that are each 1 char long) and renders it.

If the array is called `pixels`, then `pixels[0][0]` represents the top left character, `pixels[1][0]` would go below, and `pixels[0][1]` would go to the right.

Once this is done, add support for a 2D metadata array (where metadata is a custom class) that includes information about the color and style of the text being drawn.

**Comment by yj7082126** [comment]
i just added a program that takes a 2D char array and prints it. What do you exactly mean by adding support for a 2D metadata array?

**Comment by SebastianJay** [comment]
Can you draw that array without the Python list formatting? In your example it would look like:

```
0101010101
1010101010
```

and so on for all rows

Also, this should work for 1-character strings (which I call chars) and not ints.

By metadata I mean that we will have information about each character's color and style. So in our next iteration we might have a class like this (pseudocode):

```
class Char:
    string mychar
    color mycolor
    style mystyle
```

Where the string is the actual character to draw, and `color` and `style` are enums. And each element of the 2D array will actually have `Char`. Make sense?

**Comment by yj7082126** [comment]
The program I wrote should also work for chars. And what do you exactly mean by "without Python list formatting?"

**Comment by yj7082126** [comment]
import tkinter as tk

root = tk.Tk()                    # Create a background window object
                                # A simple way to create 2 lists

li     = [['a','b','a','b','a','b','a','b'],['b','a','b','a','b','a','b','a'],['a','b','a','b','a','b','a','b'],['b','a','b','a','b','a','b','a'],['a','b','a','b','a','b','a','b'],['b','a','b','a','b','a','b','a'],['a','b','a','b','a','b','a','b'],['b','a','b','a','b','a','b','a']]
listb  = tk.Listbox(root)          # Create 2 listbox widgets

for item in li:              # Insert each item inside li into the listb
    listb.insert(tk.END, item)

listb.pack()                    # Pack listbox into the main window
root.mainloop()

**Comment by yj7082126** [comment]
``` py
import tkinter as tk

root = tk.Tk()                 

li     = [['a','b','a','b','a','b','a','b'],['b','a','b','a','b','a','b','a'],['a','b','a','b','a','b','a','b'],['b','a','b','a','b','a','b','a'],['a','b','a','b','a','b','a','b'],['b','a','b','a','b','a','b','a'],['a','b','a','b','a','b','a','b'],['b','a','b','a','b','a','b','a']]
listb  = tk.Listbox(root)         

for item in li:              
    listb.insert(tk.END, item)

listb.pack()                    
root.mainloop()
```

**Comment by SebastianJay** [comment]
When I run the snippet I get:
![image](https://cloud.githubusercontent.com/assets/2125991/18981259/8f462320-86aa-11e6-9a48-be0b69bce0a2.png)

I do not want the square brackets or commas (`[`, `]`, `,`) -- I want the actual contents of the array close together.

The idea is that we'll send in strings or ASCII art via array; we don't want to break them up with commas.
